/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FavoriteType = IDL.Variant({
  'video' : IDL.Null,
  'slap' : IDL.Null,
  'photo' : IDL.Null,
});
export const Favorite = IDL.Record({
  'id' : IDL.Nat,
  'ownerPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'favoriteType' : FavoriteType,
  'targetId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AvatarConfig = IDL.Text;
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'avatarConfig' : AvatarConfig,
});
export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'createdAt' : IDL.Int,
  'uploaderPrincipal' : IDL.Principal,
  'caption' : IDL.Text,
  'galleryId' : IDL.Opt(IDL.Nat),
});
export const Slap = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'moodEmoji' : IDL.Opt(IDL.Text),
  'authorPrincipal' : IDL.Principal,
});
export const UserId = IDL.Principal;
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'uploaderPrincipal' : IDL.Principal,
});
export const TargetType = IDL.Variant({
  'video' : IDL.Null,
  'post' : IDL.Null,
  'photo' : IDL.Null,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'targetType' : TargetType,
  'targetId' : IDL.Nat,
  'authorPrincipal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addFavorite' : IDL.Func(
      [IDL.Nat, FavoriteType],
      [IDL.Variant({ 'ok' : Favorite, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteComment' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deletePhoto' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteSlap' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteVideo' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(Photo)], ['query']),
  'getSlap' : IDL.Func([IDL.Nat], [IDL.Opt(Slap)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listComments' : IDL.Func(
      [IDL.Nat, TargetType],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'listFavorites' : IDL.Func([], [IDL.Vec(Favorite)], ['query']),
  'listPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'listPhotosByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Photo)], ['query']),
  'listProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, UserProfile))],
      ['query'],
    ),
  'listSlaps' : IDL.Func([], [IDL.Vec(Slap)], ['query']),
  'listVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'postComment' : IDL.Func(
      [IDL.Nat, TargetType, IDL.Text],
      [IDL.Variant({ 'ok' : Comment, 'err' : IDL.Text })],
      [],
    ),
  'postPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : Photo, 'err' : IDL.Text })],
      [],
    ),
  'postSlap' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Slap, 'err' : IDL.Text })],
      [],
    ),
  'postVideo' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Variant({ 'ok' : Video, 'err' : IDL.Text })],
      [],
    ),
  'removeFavorite' : IDL.Func(
      [IDL.Nat, FavoriteType],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'seedSampleComments' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FavoriteType = IDL.Variant({
    'video' : IDL.Null,
    'slap' : IDL.Null,
    'photo' : IDL.Null,
  });
  const Favorite = IDL.Record({
    'id' : IDL.Nat,
    'ownerPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'favoriteType' : FavoriteType,
    'targetId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AvatarConfig = IDL.Text;
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'avatarConfig' : AvatarConfig,
  });
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'createdAt' : IDL.Int,
    'uploaderPrincipal' : IDL.Principal,
    'caption' : IDL.Text,
    'galleryId' : IDL.Opt(IDL.Nat),
  });
  const Slap = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'moodEmoji' : IDL.Opt(IDL.Text),
    'authorPrincipal' : IDL.Principal,
  });
  const UserId = IDL.Principal;
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'uploaderPrincipal' : IDL.Principal,
  });
  const TargetType = IDL.Variant({
    'video' : IDL.Null,
    'post' : IDL.Null,
    'photo' : IDL.Null,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'targetType' : TargetType,
    'targetId' : IDL.Nat,
    'authorPrincipal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addFavorite' : IDL.Func(
        [IDL.Nat, FavoriteType],
        [IDL.Variant({ 'ok' : Favorite, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteComment' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deletePhoto' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteSlap' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteVideo' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(Photo)], ['query']),
    'getSlap' : IDL.Func([IDL.Nat], [IDL.Opt(Slap)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listComments' : IDL.Func(
        [IDL.Nat, TargetType],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'listFavorites' : IDL.Func([], [IDL.Vec(Favorite)], ['query']),
    'listPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'listPhotosByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Photo)], ['query']),
    'listProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, UserProfile))],
        ['query'],
      ),
    'listSlaps' : IDL.Func([], [IDL.Vec(Slap)], ['query']),
    'listVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'postComment' : IDL.Func(
        [IDL.Nat, TargetType, IDL.Text],
        [IDL.Variant({ 'ok' : Comment, 'err' : IDL.Text })],
        [],
      ),
    'postPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : Photo, 'err' : IDL.Text })],
        [],
      ),
    'postSlap' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Slap, 'err' : IDL.Text })],
        [],
      ),
    'postVideo' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Variant({ 'ok' : Video, 'err' : IDL.Text })],
        [],
      ),
    'removeFavorite' : IDL.Func(
        [IDL.Nat, FavoriteType],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'seedSampleComments' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };