/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvatarConfig = string;
export interface Comment {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'targetType' : TargetType,
  'targetId' : bigint,
  'authorPrincipal' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface Favorite {
  'id' : bigint,
  'ownerPrincipal' : Principal,
  'createdAt' : bigint,
  'favoriteType' : FavoriteType,
  'targetId' : bigint,
}
export type FavoriteType = { 'video' : null } |
  { 'slap' : null } |
  { 'photo' : null };
export interface Photo {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'createdAt' : bigint,
  'uploaderPrincipal' : Principal,
  'caption' : string,
  'galleryId' : [] | [bigint],
}
export interface Slap {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'moodEmoji' : [] | [string],
  'authorPrincipal' : Principal,
}
export type TargetType = { 'video' : null } |
  { 'post' : null } |
  { 'photo' : null };
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'avatarConfig' : AvatarConfig,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'createdAt' : bigint,
  'description' : string,
  'viewCount' : bigint,
  'uploaderPrincipal' : Principal,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addFavorite' : ActorMethod<
    [bigint, FavoriteType],
    { 'ok' : Favorite } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteComment' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deletePhoto' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteSlap' : ActorMethod<[bigint], { 'ok' : boolean } | { 'err' : string }>,
  'deleteVideo' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPhoto' : ActorMethod<[bigint], [] | [Photo]>,
  'getSlap' : ActorMethod<[bigint], [] | [Slap]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[bigint], [] | [Video]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listComments' : ActorMethod<[bigint, TargetType], Array<Comment>>,
  'listFavorites' : ActorMethod<[], Array<Favorite>>,
  'listPhotos' : ActorMethod<[], Array<Photo>>,
  'listPhotosByUser' : ActorMethod<[Principal], Array<Photo>>,
  'listProfiles' : ActorMethod<[], Array<[UserId, UserProfile]>>,
  'listSlaps' : ActorMethod<[], Array<Slap>>,
  'listVideos' : ActorMethod<[], Array<Video>>,
  'postComment' : ActorMethod<
    [bigint, TargetType, string],
    { 'ok' : Comment } |
      { 'err' : string }
  >,
  'postPhoto' : ActorMethod<
    [string, string, ExternalBlob, [] | [bigint]],
    { 'ok' : Photo } |
      { 'err' : string }
  >,
  'postSlap' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : Slap } |
      { 'err' : string }
  >,
  'postVideo' : ActorMethod<
    [string, string, ExternalBlob],
    { 'ok' : Video } |
      { 'err' : string }
  >,
  'removeFavorite' : ActorMethod<
    [bigint, FavoriteType],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'seedSampleComments' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];